import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import MainHeader from "@/components/MainHeader";
import AuthProvider from '../context/AuthProvider';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className="min-h-screen grid grid-cols-12">
            <div className="col-span-3 bg-green-300">
              <Sidebar/>
            </div>
            <div className="col-span-9 container">
              <MainHeader/>
              <div className="main mt-10">
                {children}
              </div>
            </div>
          </div>
        </AuthProvider>     
      </body>
    </html>
  );
}
